### ISSUE TITLE
Informative model logging

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#104]
Right now we log both the "model" (decoder and default encoder) and the "module" (encoder) lookups [here](https://github.com/CUNY-CL/yoyodyne/blob/54a7e75d942f4ef3f257c6123103fadf7484efc6/yoyodyne/models/__init__.py#L35) and [here](https://github.com/CUNY-CL/yoyodyne/blob/54a7e75d942f4ef3f257c6123103fadf7484efc6/yoyodyne/models/modules/__init__.py#L53) respectively. This gives us the following printout, for a pointer-generator with a transformer encoder layer (cf. Singer & Kann 2020):

```
Model: PointerGeneratorLSTMEncoderDecoder
Model: TransformerEncoder
```

This is not as informative as it could be. I submit it would be better as something like:

```Model: transformer encoder, pointer-generator LSTM decoder```

I think this could be done by adding properties to each "model" and "module" class and then concatenating them together like:

```python
util.log_info(f"Model: {encoder.name} encoder, {model.name} decoder")
```

Thoughts? If this proposal appeals it should be easy for me to implement.

**Comment by bonham79** [comment]
oh this definitely should be improved. (espeicially the pointer gnerator atm). Preffered style would be like...

Model: Pointer Generator
   \ Source_Encoder: Transformer
   \ Feature_Encoder: Linear
   
only issue is that ptl's parameter logging is really good for quickly comparing model sizes.
