### ISSUE TITLE
train() method in train.py has incorrect args

### ISSUE THREAD

**Issue by Adamits** [CUNY-CL/yoyodyne#121]
Little bug we missed i, I assume, #110 .

We now [pass the datamodule](https://github.com/CUNY-CL/yoyodyne/blob/master/yoyodyne/train.py#L339) when calling the `train` method, but [it still expects a train and dev loader](https://github.com/CUNY-CL/yoyodyne/blob/master/yoyodyne/train.py#L216).

Without checking the docs, I suspect this works because PTL checks the type of `train_loader`, which is actually a `DataModule` with both the train and dev loaders, and uses it. Then, `dev_loader` in our method gets a string or None intended for the `train_from` arg, and since I have not tested this with `train_from`, everything was working as expected.

Easy fix that I can make today.

**Comment by kylebgorman** [comment]
Good find.
