### ISSUE TITLE
Documentation for accumulating multiple batches

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#129]
PTL allows us to simulate batch sizes larger than what will fit in your accelerator's core by accumulate gradients from multiple ("mini")batches. For instance to simulate an effective batch size of 8192 with smaller batches of 1024 one could do `--batch_size 1024 --accumulate_grad_batches 8`. Alternatively, if batch size is not known at runtime (e.g., because one is doing hyperparameter optimization) one can do `--max_batch_size 1024` and anything larger than that will be simulated like so. 

We should document this briefly.

**Comment by Adamits** [comment]
A note: I need to merge the `--max_batch_size 1024` feature in from my other fork.

**Comment by kylebgorman** [comment]
Ok I won’t document that yet.On Aug 14, 2023, at 1:03 PM, Adam ***@***.***> wrote:﻿
A note: I need to merge the --max_batch_size 1024 feature in from my other fork.
