### ISSUE TITLE
Nested tensor warning

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#214]
The transformer logs this on creation:

```UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True```

There are two things we can do about it:

1. To silence the error message but nothing else, we can add [`enable_nested_tensor=False` here](https://github.com/CUNY-CL/yoyodyne/blob/e04fedb940e94132ae729aa9df92251a3003dee4/yoyodyne/models/modules/transformer.py#L194).
2. Or we can set [`norm_first=False` here](https://github.com/CUNY-CL/yoyodyne/blob/e04fedb940e94132ae729aa9df92251a3003dee4/yoyodyne/models/modules/transformer.py#L191).

I don't know what the consequences of the latter are, really (I have no intuitions about when to norm) so I piloted it and it doesn't seem to affect performance much.

**Comment by kylebgorman** [comment]
I posted a query about it [here](https://discuss.pytorch.org/t/user-warning-about-enable-nested-tensor/206726) but nobody's responded.

**Comment by kylebgorman** [comment]
@Adamits maybe you can give me your thoughts on #224 vs #225 when you have a cchance. I am not seeing a huge performance difference.

**Comment by Adamits** [comment]
So using norm first comes form this paper: https://arxiv.org/pdf/2002.04745. I had understood this to still be the standard but have not thought much about it in a while. What performance diffs did you see?

Also, if I understand correctly, removing this allows us to enable nested tensors, which gives a better runtime efficiency, is that right?

**Comment by kylebgorman** [comment]
Nested tensors are a prototype feature in PyTorch; if certain conditions are met, they are used in the transformers implementation. I believe what actually happens is that it uses this nested tensor container the temporary data created during a forward pass.

There is an API advantage in that you can do certain operations across all the tensors grouped into the nested tensor type, but since this all happens within `nn.TransformerEncoder` and since we don't care much about the internal complexity of that class, this is irrelevant to us.

There is a potential performance advantage in that the tensors grouped into the nested tensor class are all adjacent in VRAM and some operations can be done with memory views instead of memory copies. I am not seeing a difference on my desktop; I do get slightly different results (though not in any meaningful direction) probably because norm_first does something different.

When I run transformers on my home GPU (an RTX 1660, which is by all accounts an old one), I get really bad performance: sanity-checking data loaders takes forever, and when it fires up the second worker to load the validation data, it also freezes the world for a while. This is not true with: rather small data sets, LSTMs, or if I do the computation on CPU. This is why I'm attending to transformer performance. It might be useful for someone with a different GPU to do side-by-side comparison of #224 to HEAD and/or #225.

I also want to silence any warning a user could do something about: this is not something our users can do anything about, so it should be silenced. #224 does it by disabling norm_first, which allows us to take the nested tensor "path" through the transformer encoder. #225 silences the warning by saying that we don't want to use nested tensors anyways. There is a third possibility, though I don't love it: we have a flag `--norm_first` (and `--no_norm_first`) such that if true, we take the non-nested path (and silence the warning) if false, we take the nested path (and don't norm first), and if we're not using a transforrmer encoder, neither of the above apply.

I'll read the paper in the meantime.

**Comment by Adamits** [comment]
This is all really really interesting and i'd like to learn more and test this as well, though I do not have time ATM. I will note that I had always assumed our transformer bottleneck was with inference (which would track with the data-loader sanity checking---I believe PTL runs 2 evaluation steps there.). Indeed I had a fork where I added KV-caching for inference and it seemed to 2-3x my runtime for a project where I was doing constant eval, but I found a bug in the KV-caching that I never solved and the fork got extremely stale.

**Comment by kylebgorman** [comment]
One simple possibility is to merge #225, which just silences the scary warning but doesn't otherwise change current behavior, and then investigate #224 at lower priority as an alternative.
