### ISSUE TITLE
Casting to long

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#236]
[Here](yoyodyne/data/datasets.py#L79) we cast encoded tensors to the `Long` dtype, i.e., int64. Why? Surely int32 would be enough. Is there any particular reason for this? Could we save memory by getting rid of the dtype spec?

**Comment by Adamits** [comment]
Link is broken for me, but I think casting to long is a habit I still have from learning from the pytorch tutorial that came out like 7 years ago with the initial release :D. I am not sure that it is at all necessary.

**Comment by kylebgorman** [comment]
@Adamits if I removed these casts and things work as before would you recommend that PR?

**Comment by Adamits** [comment]
32-bit seems pretty safe to me. My one reason why I am not sure is, I think the tensors are going to be 32-bit on most cuda GPUs anyway, and idk if 64-bit will really be a slow down on CPU. It could be that I dont have a good understanding though, and I don't really see many cases where just making it 32-bit would effect us.
