### ISSUE TITLE
Issue in HardAttentionLSTM

### ISSUE THREAD

**Issue by alejandromunoznavarro** [CUNY-CL/yoyodyne#258]
There is an issue in `hard_attention.py`. 
`get_decoder` is missing the parameter `embeddings` when it calls  `modules.lstm.ContextHardAttentionLSTMDecoder` (lines 413 and 433).
This could be fixed adding the line `embeddings=self.embeddings` in both calls.

**Comment by kylebgorman** [comment]
Thanks for the report, should be an easy fix. I'll take a stab at it.

**Comment by kylebgorman** [comment]
I believe I have taken care of this but let me know if anything lingers.
