### ISSUE TITLE
Use specialized prediction?

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#26]
Currently, our prediction code does [some relatively hairy stuff that is also architecture sensitive](https://github.com/CUNY-CL/yoyodyne/blob/52587bc1735b2112f1b001a41604fa8ca1d35caf/yoyodyne/predict.py#L50). Lightning permits one to define a [`predict_step` method](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#inference). If the user does not specify this, prediction is just the same as calling `forward`. 

It seems to me from this that we could likely move some of that code (the squeeze, transpose, and max) into `predict_step` for the appropriate modules, making it so that there's less Torchyness, and so we don't need to pass around or switch on the arch string.

**Comment by bonham79** [comment]
Approve of porting more logic to `predict_step`. Having model specific parts of evaluation is a personal annoyance (also my fault...)

**Comment by kylebgorman** [comment]
Cool, I'm going to assign you. It looks like some can go in the base and some in the transducer and that would cover it?

**Comment by bonham79** [comment]
Should work. Will make some of life easier anyhow. Will get to it later in the week.

**Comment by kylebgorman** [comment]
Closed in #44.
