### ISSUE TITLE
AttributeError: module 'yoyodyne.models' has no attribute 'BaseEncoderDecoder'

### ISSUE THREAD

**Issue by alejandromunoznavarro** [CUNY-CL/yoyodyne#270]
Error in predict.py at line 160: models.BaseEncoderDecoder.add_predict_argparse_args(parser)
I think it should be the 'BaseModel' class from 'yoyodyne.models.base' instead.

**Comment by kylebgorman** [comment]
Thanks for the report. This is handled in the (mostly unrelated) and pending #266, with the solution you recommend, but if you have a moment feel free to issue the one-line PR to fix it now.

**Comment by kylebgorman** [comment]
Closed in #271.
