### ISSUE TITLE
hparams

### ISSUE THREAD

**Issue by Adamits** [CUNY-CL/yoyodyne#32]
When testing, I noticed two things:

1. hparams.yaml is continuously rebuilt while training -- maybe this means we we reinstantiate the model (to load from a checkpoint or something) several times? This could be ok, but struck me as weird.
2. All samples are now in the hparams file, so it is large and gets bigger as the dataset gets bigger. This is via the training dataset property on the model I believe. I think in the past I added something to ignore certain peroperties in `hparams.yaml` but don't remember what I did off the top of my head.

I need to look into both at some point. Putting this issue here as a placeholder for now.

**Comment by kylebgorman** [comment]
(1) sounds suboptimal. (2) sounds bad, we should definitely look at that.

**Comment by Adamits** [comment]
Some observations:

1. Do we actually need to pass the entire train_set to the model? https://github.com/CUNY-CL/yoyodyne/blob/master/yoyodyne/train.py#L298 it seems that PTL stores all the arguments as hyperparamters, not those that we save as model properties as we may have though. I do not think I see any model actually use this argument -- so can we just remove it from the model kwargs? If we do need it, lightning allows us to specify only those hparams we want saved here. https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#save-hyperparameters
2. It seems that `hparams.yaml` is always remade when a lightning checkpoint is saved? From the docs I thought that the hyparameters were saved in the checkpoint, but the yaml file was **not** regenerated. I will need to do some digging to understand why this is the case...

**Comment by kylebgorman** [comment]
> 1. Do we actually need to pass the entire train_set to the model? https://github.com/CUNY-CL/yoyodyne/blob/master/yoyodyne/train.py#L298 it seems that PTL stores all the arguments as hyperparamters, not those that we save as model properties as we may have though. I do not think I see any model actually use this argument -- so can we just remove it from the model kwargs? If we do need it, lightning allows us to specify only those hparams we want saved here. https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#save-hyperparameters

Let's remove it! I thought it was required. Anything here not strictly needed, we should remove.

> 2. It seems that `hparams.yaml` is always remade when a lightning checkpoint is saved? From the docs I thought that the hyparameters were saved in the checkpoint, but the yaml file was **not** regenerated. I will need to do some digging to understand why this is the case...

May be so. If so we could prevent that that'd be good. But almost as good, we would simply not have the big training data object in it so it would be way faster and matter way less.

**Comment by Adamits** [comment]
Yeah seems like I can just remove it. I did notice though that ptr-gen and transducer error in my test runs (unrelated to removing `train_set`). I can look closer at that, but have you tested either fo those models recently?

**Comment by kylebgorman** [comment]
Just cloned and installed from HEAD, training the pointer generator on Polish now. I get this, which I hadn't seen before:

```
AttributeError: 'PaddedBatch' object has no attribute 'features_encoded'
```

Probably a copy + paste bug. I'll look into it.
