### ISSUE TITLE
Index written too late

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#35]
Currently one needs the index and a checkpoint to train. If you Ctrl+C during training, graceful shut down writes out the last checkpoint is written out, but the index is not written until training is complete. You face the same problem if you want to do predictions with an intermediate model while training is still going. The only workaround is to train zero epochs, just to get an index file.

The solution it seems is to write out the index earlier. This could either be done before training kicks off, or more fancifully, with some kind of callback.

Reported by @liliest.

**Comment by Adamits** [comment]
Looks like in some of the refactors, some logic got moved around a bit. I assume simply moving https://github.com/CUNY-CL/yoyodyne/blob/master/yoyodyne/train.py#L433 up to line 425 should solve this?

**Comment by kylebgorman** [comment]
> Looks like in some of the refactors, some logic got moved around a bit.

Yes, that's my fault.

> I assume simply moving https://github.com/CUNY-CL/yoyodyne/blob/master/yoyodyne/train.py#L433 up to line 425 should solve this?

That'd do it I think. You might need to `os.makedirs` too.

**Comment by kylebgorman** [comment]
Can I assign this to you @adamits?

**Comment by Adamits** [comment]
Yes

**Comment by kylebgorman** [comment]
> Currently one needs the index and a checkpoint to train. If you Ctrl+C during training, graceful shut down writes out the last checkpoint is written out, but the index is not written until training is complete. 

This part turns out to be incorrect BTW: 

```
 UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
Index: ../models/pointer_generator_bilstm/pol/index.pkl
Best checkpoint: ../models/pointer_generator_bilstm/pol/version_1/checkpoints/model-epoch=06-val_accuracy=0.90.ckpt
```

But the larger point that you need to "finish" (naturally, via hitting the max epochs, or via Ctrl+C) to get the index written and its location logged is correct.

**Comment by Adamits** [comment]
Ah, interesting! So control + C stops whatever the trainer is doing, and then finishes running the python program it seems?

**Comment by kylebgorman** [comment]
> Ah, interesting! So control + C stops whatever the trainer is doing, and then finishes running the python program it seems?

Yea. To say it as narrowly as possible, the `.train` method is wrapped with a `try/except KeyboardInterrupt:` or whatever.
