### ISSUE TITLE
Outputting to the current directory

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#41]
In `yoyodyne-predict`, the following will fail: `--output path_to_current_directory_file.txt`. Do you know why? It's because it tries to create the directory before writing. The simple solution, which I will now implement, will not call `os.makedir` if writing to the PWD. (We can just test for an empty string.)

Reported by @liliest

**Comment by Adamits** [comment]
What is `os.output.dirname`? As in your PR. I guess `os.path.dirname` returns an empty string, which `os.makedirs` errors on?
