### ISSUE TITLE
Feature indexing

### ISSUE THREAD

**Issue by bonham79** [CUNY-CL/yoyodyne#61]
`IndexFeatures` has an incorrect alignment for `feature_idx`. See https://github.com/CUNY-CL/yoyodyne/blob/18f19ae1858b46e1befd745f220b26106f2eb99f/yoyodyne/indexes.py#L160

 Easy fix but impacts https://github.com/CUNY-CL/yoyodyne/issues/47  Do we want to maintain a separate `features_map` to ease chance of these bugs or keep merged with `source_map`.

**Comment by kylebgorman** [comment]
I don't understand the bug (why is this wrong? ) so I am assigning the issue to you---is this related to poor performance of the feature-ified transducer?

**Comment by bonham79** [comment]
The way the index is set up, 'souece_map' includes feature vocab, so this is just providing the last index of the combined vocabularies, as opposed to the start of the feature vocabularies.

This would impact all models that treat features separately

**Comment by kylebgorman** [comment]
@bonham79 can I close this too?

**Comment by bonham79** [comment]
@kylebgorman yep1
