### ISSUE TITLE
Input/feature symbol overlap

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/yoyodyne#8]
[copied from CUNY-CL/abstractness/issues/127]

If there is any overlap between input symbols and feature symbols, the two are treated the same in several models. The simplest solution would be to use some kind of special string munging to prevent this overlap, perhaps by wrapping the features like `f"{[feature]}`. 

Alternatively, this might motivate using separate encoders for feature-full LSTM and transformer models.

Issue #7 is spiritually related.

**This is a blocker for a post-beta release candidate.**

**Comment by bonham79** [comment]
Closing issue with https://github.com/CUNY-CL/yoyodyne/pull/18
